version: '3.8'

services:
  web:
    build: ./backend
    container_name: hospital_web
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - hospital-network

  redis:
    image: redis:alpine
    container_name: hospital_redis
    ports:
      - "6379:6379"
    networks:
      - hospital-network

  celery_worker:
    build: ./backend
    container_name: hospital_celery_worker
    command: celery -A celery_tasks.celery worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - web
    networks:
      - hospital-network

  celery_beat:
    build: ./backend
    container_name: hospital_celery_beat
    command: celery -A celery_tasks.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - web
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
